server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lz92225/tensquare_config.git
#  rabbitmq:
#    host: localhost
#management: #暴露触发消息总线的地址
#  endpoints:
#    web:
#      exposure:
#        include: bus‐refresh
